[package]
name = "alang"
version = "0.0.1"
edition = "2021"
description = "Alang installer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chalk_rs = "1.0.1"
indicatif = "0.17.5"
inquire = "0.6.2"
