[package]
name = "alang"
version = "0.0.1"
edition = "2021"
description = "The ALang CLI Tool"
authors = ["AHQ"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.3", features = ["derive", "cargo"] }
