[package]
name = "packloader"
version = "0.0.3"
edition = "2021"
description = "The Alang Pack Loader"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
