[package]
name = "packager"
version = "0.0.10"
edition = "2021"
description = "Package your application"
authors = ["AHQ"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
