[package]
name = "interpreter"
version = "0.0.10"
edition = "2021"
description = "Interpret AHQ-Asm Code"
authors = ["AHQ"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
