name: ALang Builder

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        module: [".", cli, compiler, interpreter, packager, packloader]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Lang Modules
        run: cargo build
        working-directory: ${{ matrix.module }}

      - name: Install Packages
        run: npm install .
        working-directory: js

      - name: Upload for release
        run: node js/package.js
        working-directory: .
        env:
          os: ${{ matrix.os }}
          filename: ${{ matrix.module }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}

      

      