name: ALang Builder

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master

jobs:
  create_release:
    name: Make draft release
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Packages
        run: npm install .
        working-directory: js

      - name: Create Release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const {
              body,
              version
            } = await require("./js/index.js");

            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `lang-${version}`,
              name: `Alang v${version}`,
              body,
              draft: true,
              prerelease: false
            })
            return data.id

  build_and_test:
    needs: create_release
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    name: Build & Test (${{ matrix.os }})

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Lang
        run: cargo build --release

      - name: Build Cli
        run: cargo build --release
        working-directory: cli

      - name: Build Compiler
        run: cargo build --release
        working-directory: compiler

      - name: Build Interpreter
        run: cargo build --release
        working-directory: interpreter

      - name: Build Packager
        run: cargo build --release
        working-directory: packager

      - name: Build Packloader
        run: cargo build --release
        working-directory: packloader

      - name: Install Packages
        run: npm install .
        working-directory: js

      - name: Get Assets
        id: assets
        uses: actions/github-script@v6
        env:
          OS: ${{ matrix.os }}
        with:
          script: |
            const {
              installer,
              tools
            } = await require("./js/zip.js");

            return {installer, tools}

      - name: Upload Installer ${{ matrix.os }}
        uses: ahqsoftwares/upload-assets@v10
        with:
          asset-path: ${{ steps.assets.outputs.result.installer }}
          id: ${{ needs.create_release.outputs.release_id }}

      - name: Upload Tools ${{ matrix.os }}
        uses: ahqsoftwares/upload-assets@v11
        with:
          asset-path: ${{ steps.assets.outputs.result.tools }}
          id: ${{ needs.create_release.outputs.release_id }}

      

      